# Generated by Django 4.2.7 on 2024-04-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("flaticon-web-development", "flaticon-web-development"),
                            ('"flaticon-web-domain', '"flaticon-web-domain'),
                            ("flaticon-nanotechnology", "flaticon-nanotechnology"),
                            ("flaticon-profile", "flaticon-profile"),
                            ("flaticon-search", "flaticon-search"),
                        ],
                        max_length=255,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="")),
                ("title_info", models.CharField(max_length=255)),
                ("number_info", models.IntegerField(max_length=2)),
                ("text_info", models.TextField()),
            ],
        ),
    ]
