# Generated by Django 4.2.7 on 2024-04-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="icon",
            field=models.CharField(
                choices=[
                    ("flaticon-web-development", "flaticon-web-development"),
                    ("flaticon-web-domain", "flaticon-web-domain"),
                    ("flaticon-nanotechnology", "flaticon-nanotechnology"),
                    ("flaticon-profile", "flaticon-profile"),
                    ("flaticon-search", "flaticon-search"),
                ],
                max_length=255,
            ),
        ),
    ]
