# Generated by Django 4.2.7 on 2024-04-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_services_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
