# Generated by Django 4.2.7 on 2024-05-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_alter_services_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="services",
            name="icon",
            field=models.ImageField(upload_to="foods/"),
        ),
        migrations.AlterField(
            model_name="services",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="foods/"),
        ),
    ]
