# Generated by Django 4.2.7 on 2024-05-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_alter_services_icon_alter_services_image"),
    ]

    operations = [
        migrations.DeleteModel(name="Services",),
    ]
