# Generated by Django 4.2.7 on 2024-06-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_ourteam"),
    ]

    operations = [
        migrations.RemoveField(model_name="ourteam", name="social_media_link",),
        migrations.AddField(
            model_name="ourteam",
            name="facebook_social_media_link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ourteam",
            name="instagram_social_media_link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ourteam",
            name="twiter_social_media_link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ourteam",
            name="youtube_social_media_link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
