# Generated by Django 4.2.7 on 2024-06-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_remove_ourteam_social_media_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("text", models.TextField()),
            ],
        ),
    ]
