# Generated by Django 4.2.7 on 2024-07-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.PositiveIntegerField(max_length=20)),
                ("description", models.TextField()),
                (
                    "popular_field",
                    models.CharField(
                        choices=[("popular", "p"), ("unpopular", "up")], max_length=100
                    ),
                ),
            ],
        ),
    ]
