# Generated by Django 4.2.7 on 2024-07-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="popular_field",
            field=models.CharField(
                choices=[("popular", "popular"), ("unpopular", "unpopular")],
                max_length=100,
            ),
        ),
    ]
