# Generated by Django 4.2.7 on 2024-06-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cover",
            field=models.ImageField(default=2, upload_to="post/"),
            preserve_default=False,
        ),
    ]
