# Generated by Django 4.2.7 on 2024-06-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author_avatar",
            field=models.ImageField(default=2, upload_to="author_avatar/"),
            preserve_default=False,
        ),
    ]
