# Generated by Django 4.2.7 on 2024-06-06 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_portfolio_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolios",
                to="portfolio.category",
            ),
        ),
    ]
